//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fliper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class polubienia
    {
        public int id { get; set; }
        public string odkogo { get; set; }
        public string dlakogo { get; set; }
        public bool IsShowed { get; set; }
    }
}
