//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fliper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileInfo
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string colubie { get; set; }
        public string opis { get; set; }
        public string pseudomin { get; set; }
        public string phonenumber { get; set; }
        public Nullable<short> waga { get; set; }
        public Nullable<short> wzrost { get; set; }
        public string favcolor { get; set; }
        public string samochod { get; set; }
    }
}
