//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fliper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zainteresowania
    {
        public int id { get; set; }
        public string nazwa { get; set; }
        public string zdjecie { get; set; }
        public Nullable<int> ileOsob { get; set; }
        public string autor { get; set; }
    }
}
